services:
  robot-appium:
    build:
      context: .
      dockerfile: config/docker/robot-appium/Dockerfile
    environment:
      - DOCKER_ADB_HOST=true
    ports:
      - 4723:4723
    volumes:
      - ./tests:/home/androidusr/tests
      - /dev/bus/usb:/dev/bus/usb
      - ~/.android:/root/.android
    privileged: true
    platform: linux/amd64
    # command: "robot tests/mobile/robot/test.robot"

  taurus-selenium-jmeter:
    build:
      context: .
      dockerfile: config/docker/taurus-selenium-jmeter/Dockerfile
    container_name: taurus-selenium-jmeter
    volumes:
      - ./tests:/bzt-configs/tests
      - ./results:/bzt-configs/results
    platform: linux/amd64

  