services:
  robot-appium:
    build:
      context: .
      dockerfile: config/docker/robot-appium/Dockerfile
    container_name: robot-appium
    environment:
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=selenium_hub
      - REMOTE_ADB=true
      - REMOTE_ADB_POLLING_SEC=60
    ports:
      - 4723:4723
    volumes:
      - ./tests:/home/androidusr/tests
      - /dev/bus/usb:/dev/bus/usb
      - ~/.android:/root/.android
    privileged: true
    platform: linux/amd64
    # command: "robot tests/mobile/robot/test.robot"

  selenium-jmeter:
    build:
      context: .
      dockerfile: config/docker/selenium-jmeter/Dockerfile
    container_name: selenium-jmeter
    volumes:
      - ./tests:/bzt-configs/tests
      - ./results:/bzt-configs/results
    platform: linux/amd64

  